# Generated by Django 3.2.16 on 2023-02-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_order_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
    ]
