# Generated by Django 3.2.16 on 2023-02-15 15:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.CharField(default='false', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='measurements',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
