# Generated by Django 3.2.16 on 2023-02-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_order_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='measurements',
        ),
    ]
