# Generated by Django 3.2.16 on 2023-02-15 18:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_remove_order_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurements',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
