# Generated by Django 3.2.16 on 2023-02-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_order_measurements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Delivery',
        ),
    ]
