# Generated by Django 3.2.16 on 2023-02-17 14:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20230217_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered',
            field=models.CharField(choices=[('false', 'Not Delivered'), ('true', 'Delivered')], default='false', max_length=200),
        ),
        migrations.AddField(
            model_name='delivery',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='delivery',
            name='measurements',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
