# Generated by Django 3.2.16 on 2023-02-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_remove_delivery_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
