# Generated by Django 3.2.16 on 2023-02-17 16:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_auto_20230217_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='measurements',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
