# Generated by Django 3.2.16 on 2023-02-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_delivery_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
