# Generated by Django 3.2.16 on 2023-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_alter_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='items',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
