# Generated by Django 3.2.16 on 2023-01-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=50, unique=True)),
                ('cloth_image', models.CharField(max_length=300)),
                ('cloth_category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('complete', 'Complete')], default='top', max_length=8)),
                ('cloth_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='male', max_length=8)),
                ('cloth_price', models.FloatField()),
                ('cloth_description', models.TextField()),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
            ],
        ),
    ]
