# Generated by Django 3.2.16 on 2023-01-25 17:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='cloth_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
